/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.SerbisyongBarangay;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // CheckDocumentStatusFrame ch=new CheckDocumentStatusFrame();

        
        userMain user=new userMain();
        user.setVisible(true);
    }
}
